### ISSUE TITLE
Bug on import

### ISSUE THREAD

**Issue by gbuchbi** [postvakje/oeis-sequences#1]
On Python 3.9.18, I am getting a SyntaxError on import, which seems to be related to the sequence A358348, below:
`def A358348(n):
    return (0, 1, 4, 7, 9, 10, 13, 16, 17)[m:=n % 9] + (n - m << 1)`
I think this is happening because colons are used in the slice notation to separate the [start:end:step].

It seems to be fixed by surrounding the slice index with parentheses:
`def A358348(n):
    return (0, 1, 4, 7, 9, 10, 13, 16, 17)[(m:=n % 9)] + (n - m << 1)`

**Comment by postvakje** [comment]
Thank you for finding this bug. It has now been fixed.
