### ISSUE TITLE
oeis sequence transforms

### ISSUE THREAD

**Issue by grue-bleen** [postvakje/oeis-sequences#3]
thanks for your awesome contribution!  🙏

oeis sequences have maple, mathematica, and pari support for both programs and transforms:
  - https://oeis.org/transforms.html
  - https://oeis.org/transforms2.html

sympy based support for sequence transforms would be a great addition to the oeis community.  any thoughts/ideas on this approach and key gaps?

**Comment by postvakje** [comment]
Thank you! Currently the run length transform and Boustrophedon transform are available. I will add other transforms periodically.
